-- président de chaque club
SELECT CLUB.NOM_CLUB, RESPONSABLE.NOM_RESPONSABLE, RESPONSABLE.PRENOM_RESPONSABLE
FROM CLUB, RESPONSABLE
WHERE CLUB.NUMERO_CLUB = RESPONSABLE.NUMERO_CLUB
AND RESPONSABLE.FONCTION = 'PRESIDENT';

-- score des matchs joués
SELECT RENCONTRE.DATE_RENCONTRE, RENCONTRE.NUMERO_RENCONTRE, RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE, RENCONTRE.SCORE_EQUIPE_DOMICILE, RENCONTRE.SCORE_EQUIPE_EXTERIEUR, RENCONTRE.NUMERO_EQUIPE_JOUE_EXTERIEUR
FROM RENCONTRE
ORDER BY RENCONTRE.NUMERO_RENCONTRE ASC;

--Moyenne de points par rencontre pour une journée
select SUM(POINTS_MARQUES_RENCONTRE)/
       (select count(NUMERO_JOURNEE) select RENCONTRE
       	        where NUMERO_JOURNEE = 1) 
as MOYENNE POINTS MARQUES, NUMERO_JOURNEE from 
   (select NUMERO_JOURNEE, NUMERO_RENCONTRE, SCORE_EQUIPE_DOMICILE+SCORE_EQUIPE_EXTERIEUR as POINTS_MARQUES_RENCONTRE from RENCONTRE where NUMERO_JOURNEE = 1) as TAB

--Requetes victoires equipes
select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES
from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as RTR_L
left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE;

-- GOALAVERAGE
--différence domicile, exterieur, général
select RTR_L.NUMERO_EQUIPE, ifnull(DIFF_DOMICILE,0) as GOALAVERAGE_DOMICILE, ifnull(DIFF_EXTERIEUR,0) as GOALAVERAGE_EXTERIEUR, ifnull(DIFF_DOMICILE,0)+ifnull(DIFF_EXTERIEUR,0) as GOALAVERAGE_GENERAL
from (select NUMERO_EQUIPE, sum(SCORE_EQUIPE_DOMICILE-SCORE_EQUIPE_EXTERIEUR) AS DIFF_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    group by NUMERO_EQUIPE) as GOAL_L
left join    (select NUMERO_EQUIPE, sum(SCORE_EQUIPE_EXTERIEUR-SCORE_EQUIPE_DOMICILE) AS DIFF_EXTERIEUR
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_EXTERIEUR = EQUIPE.NUMERO_EQUIPE
    group by NUMERO_EQUIPE) GOAL_R
on GOAL_L.NUMERO_EQUIPE = GOAL_R.NUMERO_EQUIPE

--Requete victoire equipe domicile avec contrainte catégorie
select VIC_DOM.NUMERO_EQUIPE, VIC_DOM.NOMBRE_VICTOIRE_DOMICILE, NOM_CATEGORIE

from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NOMBRE_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as VIC_DOM, EQUIPE
where EQUIPE.NOM_CATEGORIE = 'SENIOR'
and VIC_DOM.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
order by NOMBRE_VICTOIRE_DOMICILE desc;

--Requetes victoire equipe avec contrainte de catégorie
select VIC.NUMERO_EQUIPE, VIC.NOMBRE_VICTOIRES, NOM_CATEGORIE
from(
select RTR_L.NUMERO_EQUIPE, ifnull(NB_VICTOIRE_DOMICILE,0)+ifnull(NB_VICTOIRE_EXTERIEUR,0) as NOMBRE_VICTOIRES
from (select NUMERO_EQUIPE, COUNT(RENCONTRE.NUMERO_RENCONTRE) AS NB_VICTOIRE_DOMICILE
    from EQUIPE
    left join RENCONTRE
    on RENCONTRE.NUMERO_EQUIPE_JOUE_DOMICILE = EQUIPE.NUMERO_EQUIPE
    and SCORE_EQUIPE_DOMICILE > SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE) as RTR_L
left join (select NUMERO_EQUIPE_JOUE_EXTERIEUR AS NUMERO_EQUIPE, COUNT(NUMERO_RENCONTRE) AS NB_VICTOIRE_EXTERIEUR
    from RENCONTRE
    where SCORE_EQUIPE_DOMICILE < SCORE_EQUIPE_EXTERIEUR
    group by NUMERO_EQUIPE_JOUE_EXTERIEUR) as RTR_R
on RTR_L.NUMERO_EQUIPE = RTR_R.NUMERO_EQUIPE)
as VIC, EQUIPE
where EQUIPE.NOM_CATEGORIE = 'SENIOR'
and VIC.NUMERO_EQUIPE = EQUIPE.NUMERO_EQUIPE
order by NOMBRE_VICTOIRES desc;
